theme = "hugo-theme-minos"

baseURL = "https://blog.yjtseng.info/"

languageCode = "zh-tw"
title = "有完沒完RRR"
enableEmoji = true
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
SmartToc = true
disqusShortname = "rrrblog"

[[menu.main]]
    name = "Categories"
    url= "/Categories/index.html"
    weight = 1
[[menu.main]]
    name = "Tags"
    url="/Tags/index.html"
    weight = 2
    
[[menu.main]]
    name = "About"
    url = "https://yjtseng.info/"
    weight = 3
    
[params]
    smartToc = true
    SmartToc = true
    author = "Yi-Ju Tseng"
    googleAnalytics = "UA-2407708-4"

[taxonomies]
  category = "categories"
  tag = "tags"