---
title: 使用tidymodel建立預測模型
author: Yi-Ju Tseng
date: '2020-05-14'
slug: tidymodel
categories:
  - R language
tags:
  - R
  - Data Mining
---


```{r global options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

人工智慧/機器學習/資料探勘正夯，剛好`tidymodels`套件的[官網](https://www.tidymodels.org/)上線了，順勢介紹由`caret`套件的開發者[Max Kuhn](https://twitter.com/topepos)開發的全新建模架構。如同套件名稱，`tidymodels`套件的撰寫邏輯和方法與`tidyverse`套件組合相同，若熟悉`dplyr`、`ggplot`等套件應該蠻好上手

第一次使用前一樣要先安裝
```{r eval=F}
install.packages("tidymodels")
```

安裝後即可載入
```{r}
library(tidymodels)
```

## 建模範例資料
```{r}
library(mlbench)
data("BostonHousing")
data("PimaIndiansDiabetes2")
```

## 訓練組與測試組資料分割

```{r}
set.seed(123)
splits<- initial_split(PimaIndiansDiabetes2, 
                       strata = diabetes)
DM_train<- training(splits)
DM_test<- testing(splits)
```

```{r}
set.seed(234)
val_set <- validation_split(DM_train, 
                            strata = diabetes, 
                            prop = 0.75)
val_set
```

## 建立資料前處理“食譜”

```{r}
lr_recipe <- 
  recipe(diabetes ~ ., data = DM_train) %>% 
  step_naomit(everything(), skip = TRUE) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())
```

## 決定要用什麼演算法建立模型

```{r}
lr_mod <- 
  logistic_reg(penalty = tune(), mixture = 0.5) %>% 
  set_engine("glmnet")
```


## 決定參數調整數列

```{r}
lr_reg_grid <- 
  tibble(penalty = 10^seq(-4, -1, length.out = 50))
lr_reg_grid %>% head()
```

## 決定

```{r}
lr_workflow <- 
  workflow() %>% 
  add_model(lr_mod) %>% 
  add_recipe(lr_recipe)

lr_res <- 
  lr_workflow %>% 
  tune_grid(val_set,
            grid = lr_reg_grid,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))
```


```{r}
lr_plot <- 
  lr_res %>% 
  collect_metrics() %>% 
  ggplot(aes(x = penalty, y = mean)) + 
  geom_point() + 
  geom_line() + 
  ylab("Area under the ROC Curve") +
  scale_x_log10(labels = scales::label_number())

lr_plot 
```

```{r}
top_models <-
  lr_res %>% 
  show_best("roc_auc", n = 15) %>% 
  arrange(penalty) 
top_models
```

```{r}
lr_best <- lr_res %>% 
  show_best("roc_auc", n = 1)
lr_best
```

```{r}
lr_res %>% 
  collect_predictions()
```

```{r}
lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_auc(diabetes, .pred_pos)
```

```{r}
lr_auc <- 
  lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_curve(diabetes, .pred_pos) %>% 
  mutate(model = "Logistic Regression")

autoplot(lr_auc)
lr_auc
```

## Evaluation

```{r}
set.seed(345)
folds <- vfold_cv(DM_train, 
                  v = 5)
folds
```

```{r}
lr_recipe_evl <- 
  recipe(diabetes ~ ., data = PimaIndiansDiabetes2) %>% 
  step_naomit(everything(), skip = TRUE) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())

lr_mod_evl <- 
  logistic_reg(penalty = 0.01, mixture = 0.5) %>% 
  set_engine("glmnet")

control <- control_resamples(save_pred = TRUE)
set.seed(456)
spline_res <- fit_resamples(lr_mod_evl, lr_recipe_evl, folds, control = control)
spline_res %>% 
  collect_metrics(summarize = TRUE)

```